---
version: '3.7'
services:
        backend:
                build:
                        context: ./back
                        dockerfile: ./Dockerfile
                container_name: backend
                restart: unless-stopped
                volumes:
                        - ./taste-log:/home/taste/src/logs
                expose:
                        - ${APP_PORT}
                env_file:
                        - .back_env
                networks:
                        - proxy
        front:
                build:
                        context: ./front
                        dockerfile: ./Dockerfile
                container_name: admin_front
                restart: unless-stopped
                volumes:
                        - ./front/public:/app/public
                expose:
                        - ${APP_PORT}
                env_file:
                        - .front_env
                networks:
                        - proxy
networks:
        proxy:
                external: true
